---
- name: Create volume
  ec2_vol:
    name: '{{ cloud_volume_name }}'
    volume_size: '{{ cloud_volume_size }}'
    region: '{{ cloud_volume_region.split(":")[0] }}'
    state: '{{ cloud_volume_state|default("present") }}'
    zone: '{{ cloud_volume_region.split(":")[1] }}'
