---
- name: Manage volume
  os_volume:
    display_name: '{{ cloud_volume_name }}'
    size: '{{ cloud_volume_size }}'
    availability_zone: '{{ cloud_volume_region }}'
    state: '{{ cloud_volume_state|default("present") }}'
